#!/bin/bash
# Please update dirs accordingly

#BSUB -J spaceranger-sample
#BSUB -W 3:00
#BSUB -o /rsrch5/scratch/trans_mol_path/xpan7/pipelines/logs/%J_lsf.out
#BSUB -e /rsrch5/scratch/trans_mol_path/xpan7/pipelines/logs/%J_lsf.err
#BSUB -q short
#BSUB -n 16
#BSUB -M 128
#BSUB -R rusage[mem=128]


module load ImageMagick/7.1.0-44
cd /rsrch6/home/trans_mol_path/yuan_lab/TIER1/anthracosis/visium_TMA5primary_2014-/HE40x_tif
magick TMA5-157-svs.tif -define tiff:tile-geometry=256x256 -units PixelsPerCentimeter -compress LZW ptif:TMA5-157-svs-pyramid.tiff